name: tcg_generator
channels:
  - conda-forge
  - pytorch
  - nivida
dependencies:

# Classic pydata_packages

  - python
  - ipython
  - jupyterlab
  - pip

  # Formating and make things look nice
  - black
  - flake8
  - isort
  - typer
  - loguru
  - tqdm
  - python-dotenv

# Data Science packages
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - seaborn

# Specific packages for tcg_generator

  # NLP work
  - nltk
  - spacy
  - gensim

  - pip:

    # Huggingface items
    - diffusers
    - transformers
    - tokenizers
  # - accelerate # If you've got a good GPU this'll work... I don't think a 1070 will support it


    # Pytorch and related packages - Pip install your own pytorch version
    # - pytorch==2.5.1 # pytorch 2.6.0 is pip install only
    # - pytorch-cuda=11.8 # Specific to your GPU setup
    # - torchtext


    - Flask
    - python-dotenv
    # - mkdocs
    - -e . # developer install of this package