name: tcg_generator
channels:
  - conda-forge
dependencies:

  # Classic pydata_packages
  - python=3.10
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn

  # Specific packages for tcg_generator



  # Sphinx stuff we probably won't use for a project this short...

  - pip:
    - python-dotenv
    - mkdocs
    - -e . # developer install of this package