THEME_OPTIONS = [
    "+1/+1 Counters",
    "-1/-1 Counters",
    "A Counters",
    "Acorn Counters",
    "Activated Abilities",
    "Adamant",
    "Adapt",
    "Addendum",
    "Additional Combat",
    "Adorned Pouncer Tokens",
    "Aegis Counters",
    "Aetherborn Tokens",
    "Affinity",
    "Afflict",
    "Afterlife",
    "Agate Instigator Tokens",
    "Age Counters",
    "Aim Counters",
    "Ajani's Pridemate Tokens",
    "Alien Angel Tokens",
    "Alien Insect Tokens",
    "Alien Rhino Tokens",
    "Alien Salamander Tokens",
    "Alien Tokens",
    "Alien Warrior Tokens",
    "All Counters",
    "Alliance",
    "Alternative Cost",
    "Amass",
    "Amplify",
    "And Counters",
    "Angel Tokens",
    "Angel Warrior Tokens",
    "Angel of Sanctions Tokens",
    "Annihilator",
    "Anointer Priest Tokens",
    "Any Number Of",
    "Ape Tokens",
    "Arco-Flagellant Tokens",
    "Arrow Counters",
    "Arrowhead Counters",
    "Art Counters",
    "Artifact Based",
    "Ascend",
    "Ashaya, the Awoken World Tokens",
    "Assassin Tokens",
    "Assembly-Worker Tokens",
    "Assist",
    "Astartes Warrior Tokens",
    "Attacking",
    "Aura",
    "Avacyn Tokens",
    "Avatar Tokens",
    "Aven Initiate Tokens",
    "Aven Wind Guide Tokens",
    "Awaken",
    "Awakening Counters",
    "B Color",
    "B Identity",
    "BG Color",
    "BG Identity",
    "BGR Color",
    "BGR Identity",
    "BGRU Color",
    "BGRU Identity",
    "BGRUW Color",
    "BGRUW Identity",
    "BGRW Color",
    "BGRW Identity",
    "BGU Color",
    "BGU Identity",
    "BGUW Color",
    "BGUW Identity",
    "BGW Color",
    "BGW Identity",
    "BR Color",
    "BR Identity",
    "BRU Color",
    "BRU Identity",
    "BRUW Color",
    "BRUW Identity",
    "BRW Color",
    "BRW Identity",
    "BU Color",
    "BU Identity",
    "BUW Color",
    "BUW Identity",
    "BW Color",
    "BW Identity",
    "Backup",
    "Badger Tokens",
    "Bait Counters",
    "Ballistic Boulder Tokens",
    "Balloon Tokens",
    "Banding",
    "Bargain",
    "Bat Tokens",
    "Battalion",
    "Battle Cry",
    "Bear Tokens",
    "Beast Tokens",
    "Beau Tokens",
    "Becomes Tapped",
    "Beeble Tokens",
    "Bestow",
    "Bird Illusion Tokens",
    "Bird Soldier Tokens",
    "Bird Tokens",
    "Blaze Counters",
    "Blessing Counters",
    "Blight Counters",
    "Blitz",
    "Blood Counters",
    "Blood Tokens",
    "Bloodstain Counters",
    "Bloodthirst",
    "Blue Horror Tokens",
    "Boar Tokens",
    "Boardwipe",
    "Boast",
    "Bolster",
    "Boo Tokens",
    "Book Counters",
    "Bounty Counters",
    "Brain Counters",
    "Brainiac Tokens",
    "Bribery Counters",
    "Brick Counters",
    "Burden Counters",
    "Burn Counters",
    "Bushido",
    "Bushy Bodyguard Tokens",
    "Butterfly Tokens",
    "Buyback",
    "Cage Counters",
    "Card Draw",
    "Carnivore Tokens",
    "Carrion Counters",
    "Cascade",
    "Casualty",
    "Cat Beast Tokens",
    "Cat Bird Tokens",
    "Cat Dragon Tokens",
    "Cat Soldier Tokens",
    "Cat Tokens",
    "Cat Warrior Tokens",
    "Celebration",
    "Centaur Tokens",
    "Champion",
    "Champion of Wits Tokens",
    "Changeling",
    "Channel",
    "Charge Counters",
    "Cherubael Tokens",
    "Chip Counters",
    "Choose a Background",
    "Chorus Counters",
    "Chroma",
    "Cipher",
    "Citizen Tokens",
    "Clash",
    "Cleave",
    "Cleric Tokens",
    "Cloak",
    "Clone",
    "Cloud Sprite Tokens",
    "Clown Robot Tokens",
    "Clue Tokens",
    "Cohort",
    "Coin Counters",
    "Collect Evidence",
    "Collection Counters",
    "Combat Damage",
    "Commit a Crime",
    "Companion",
    "Compleated",
    "Component Counters",
    "Connive",
    "Conspire",
    "Constellation",
    "Construct Tokens",
    "Contested Counters",
    "Control Counters",
    "Convoke",
    "Copy Tokens",
    "Corpse Counters",
    "Corrupted",
    "Corruption Counters",
    "Coruscation Mage Tokens",
    "Council's Dilemma",
    "Counterspell",
    "Coven",
    "Crab Tokens",
    "Cragflame Tokens",
    "Creature Based",
    "Credit Counters",
    "Crew",
    "Croak Counters",
    "Crystal Counters",
    "Cube Counters",
    "Cumulative Upkeep",
    "Currency Counters",
    "Curse",
    "Cycling",
    "Dalek Tokens",
    "Damage",
    "Darkstar Augur Tokens",
    "Dash",
    "Day Counters",
    "Death Counters",
    "Deathtouch",
    "Deathtouch Counters",
    "Decayed",
    "Defender",
    "Defense Counters",
    "Delay Counters",
    "Delirium",
    "Delve",
    "Demon Berserker Tokens",
    "Demon Tokens",
    "Demonstrate",
    "Depletion Counters",
    "Descend",
    "Descent Counters",
    "Desert",
    "Despair Counters",
    "Detain",
    "Detective Tokens",
    "Dethrone",
    "Devil Tokens",
    "Devoid",
    "Devotion",
    "Devotion Counters",
    "Devour",
    "Dies",
    "Different Counters",
    "Dinosaur Beast Tokens",
    "Dinosaur Cat Tokens",
    "Dinosaur Egg Tokens",
    "Dinosaur Tokens",
    "Discard",
    "Discover",
    "Discovery Counters",
    "Disguise",
    "Divinity Counters",
    "Djinn Monk Tokens",
    "Dog Illusion Tokens",
    "Dog Tokens",
    "Domain",
    "Doom Counters",
    "Double Strike",
    "Dragon Egg Tokens",
    "Dragon Elemental Tokens",
    "Dragon Illusion Tokens",
    "Dragon Spirit Tokens",
    "Dragon Tokens",
    "Drain",
    "Drake Tokens",
    "Dread Counters",
    "Dream Counters",
    "Dreamstealer Tokens",
    "Dredge",
    "Drone Tokens",
    "Dungeon",
    "Duty Counters",
    "Dwarf Berserker Tokens",
    "Dwarf Tokens",
    "Each Counters",
    "Earthshaker Khenra Tokens",
    "Echo",
    "Echo Counters",
    "Eerie",
    "Egg Counters",
    "Egg Tokens",
    "Eldrazi Angel Tokens",
    "Eldrazi Horror Tokens",
    "Eldrazi Scion Tokens",
    "Eldrazi Spawn Tokens",
    "Eldrazi Tokens",
    "Elemental Bird Tokens",
    "Elemental Shaman Tokens",
    "Elemental Tokens",
    "Elephant Tokens",
    "Elf Druid Tokens",
    "Elf Knight Tokens",
    "Elf Warrior Tokens",
    "Elixir Counters",
    "Elk Tokens",
    "Embalm",
    "Emerge",
    "Eminence",
    "Enchantment Based",
    "Encore",
    "Energy",
    "Enlightened Counters",
    "Enlist",
    "Enrage",
    "Entwine",
    "Eon Counters",
    "Epic",
    "Equipment",
    "Eruption Counters",
    "Escalate",
    "Escape",
    "Eternalize",
    "Etherium Cell Tokens",
    "Everything Counters",
    "Everywhere Tokens",
    "Evoke",
    "Evolve",
    "Exalted",
    "Exalted Counters",
    "Exchange",
    "Exert",
    "Experience Counters",
    "Exploit",
    "Explore",
    "Exposure Counters",
    "Extort",
    "Extra Lands",
    "Eyeball Counters",
    "Eyestalk Counters",
    "Fabricate",
    "Fade Counters",
    "Fading",
    "Faerie Dragon Tokens",
    "Faerie Rogue Tokens",
    "Faerie Spy Tokens",
    "Faerie Tokens",
    "Fanatic of Rhonas Tokens",
    "Fate Counters",
    "Fateseal",
    "Fear",
    "Feather Counters",
    "Feather Tokens",
    "Feeding Counters",
    "Fellowship Counters",
    "Ferocious",
    "Fetch Counters",
    "Fights",
    "Filibuster Counters",
    "Finality Counters",
    "Finch Formation Tokens",
    "First Mate Ragavan Tokens",
    "First Strike",
    "Fish Tokens",
    "Five Counters",
    "Flame Counters",
    "Flanking",
    "Flash",
    "Flashback",
    "Flicker",
    "Flip a Coin",
    "Flood Counters",
    "Flowerfoot Swordmaster Tokens",
    "Flying",
    "Flying Counters",
    "Fog",
    "Food",
    "Food Tokens",
    "For Mirrodin",
    "Forage",
    "Forecast",
    "Foreshadow Counters",
    "Forest Dryad Tokens",
    "Foretell",
    "Formidable",
    "Fortify",
    "Fox Tokens",
    "Fractal Tokens",
    "Free Spells",
    "Freerunning",
    "Frog Lizard Tokens",
    "Fungus Beast Tokens",
    "Fungus Counters",
    "Fungus Dinosaur Tokens",
    "Fungus Tokens",
    "Funk Counters",
    "Fury Counters",
    "Fuse Counters",
    "G Color",
    "G Identity",
    "GR Color",
    "GR Identity",
    "GRU Color",
    "GRU Identity",
    "GRUW Color",
    "GRUW Identity",
    "GRW Color",
    "GRW Identity",
    "GU Color",
    "GU Identity",
    "GUW Color",
    "GUW Identity",
    "GW Color",
    "GW Identity",
    "Gain Control",
    "Gargoyle Tokens",
    "Gem Counters",
    "Germ Tokens",
    "Get Counters",
    "Ghostform Counters",
    "Giant Teddy Bear Tokens",
    "Giant Tokens",
    "Giant Warrior Tokens",
    "Giant Wizard Tokens",
    "Gift",
    "Glass Counters",
    "Glimmer Tokens",
    "Globe Counters",
    "Glyph Counters",
    "Glyph Keeper Tokens",
    "Gnome Soldier Tokens",
    "Gnome Tokens",
    "Goad",
    "Goat Tokens",
    "Goblin Construct Tokens",
    "Goblin Rogue Tokens",
    "Goblin Shaman Tokens",
    "Goblin Soldier Tokens",
    "Goblin Tokens",
    "Goblin Warrior Tokens",
    "Goblin Wizard Tokens",
    "Gold Counters",
    "Gold Tokens",
    "Golem Tokens",
    "Graft",
    "Graveborn Tokens",
    "Gravestorm",
    "Gremlin Tokens",
    "Griffin Tokens",
    "Growth Counters",
    "Guenhwyvar Tokens",
    "Hack Counters",
    "Had Counters",
    "Hamster Tokens",
    "Harmony Counters",
    "Harpy Tokens",
    "Haste",
    "Haste Counters",
    "Hatchling Counters",
    "Haunt",
    "Have Counters",
    "Healing Counters",
    "Heart-Piercer Manticore Tokens",
    "Hellbent",
    "Hellion Tokens",
    "Heroic",
    "Hexproof",
    "Hexproof Counters",
    "Hideaway",
    "Hippo Tokens",
    "Hit Counters",
    "Hole Counters",
    "Homunculus Tokens",
    "Honored Hydra Tokens",
    "Hoofprint Counters",
    "Hope Counters",
    "Hornet Tokens",
    "Horror Tokens",
    "Horse Tokens",
    "Horsemanship",
    "Hour Counters",
    "Hourglass Counters",
    "Human Cleric Tokens",
    "Human Knight Tokens",
    "Human Monk Tokens",
    "Human Noble Tokens",
    "Human Rogue Tokens",
    "Human Soldier Tokens",
    "Human Tokens",
    "Human Warrior Tokens",
    "Human Wizard Tokens",
    "Hunger Counters",
    "Husk Counters",
    "Hydra Tokens",
    "Ice Counters",
    "Icingdeath, Frost Tongue Tokens",
    "Icy Manalith Tokens",
    "Illusion Tokens",
    "Imp Tokens",
    "Impostor Counters",
    "Imprint",
    "Improvise",
    "Incarnation Counters",
    "Incubate",
    "Incubation Counters",
    "Indestructible",
    "Indestructible Counters",
    "Infect",
    "Infection Counters",
    "Influence Counters",
    "Ingenuity Counters",
    "Ingredient Counters",
    "Initiative",
    "Inkling Tokens",
    "Insect Tokens",
    "Inspired",
    "Instead Counters",
    "Intervention Counters",
    "Intimidate",
    "Intrepid Rabbit Tokens",
    "Investigate",
    "Iridescent Vinelasher Tokens",
    "Isolation Counters",
    "Its Counters",
    "Javelin Counters",
    "Jump-start",
    "Junk Tokens",
    "Karox Bladewing Tokens",
    "Kavu Tokens",
    "Keimi Tokens",
    "Keyword Counters",
    "Ki Counters",
    "Kick Counters",
    "Kicker",
    "Kinship",
    "Kithkin Soldier Tokens",
    "Knight Ally Tokens",
    "Knight Tokens",
    "Knowledge Counters",
    "Kobolds of Kher Keep Tokens",
    "Koma's Coil Tokens",
    "Kor Ally Tokens",
    "Kor Soldier Tokens",
    "Kor Warrior Tokens",
    "Kraken Tokens",
    "Labyrinth Guardian Tokens",
    "Land Mine Tokens",
    "Landfall",
    "Landwalk",
    "Laserbeak Tokens",
    "Level Counters",
    "Level Up",
    "Lieutenant",
    "Lifegain",
    "Lifelink",
    "Lifelink Counters",
    "Lightning Rager Tokens",
    "Living Weapon",
    "Lizard Tokens",
    "Llanowar Elves Tokens",
    "Loot Counters",
    "Lore Counters",
    "Loyalty Counters",
    "Luck Counters",
    "Madness",
    "Magecraft",
    "Magnet Counters",
    "Manabond Counters",
    "Manifest",
    "Manifestation Counters",
    "Manifold Mouse Tokens",
    "Mannequin Counters",
    "Many Counters",
    "Map Tokens",
    "Marit Lage Tokens",
    "Mark of the Rani Tokens",
    "Mask Tokens",
    "Matrix Counters",
    "May Counters",
    "Mechtitan Tokens",
    "Megamorph",
    "Meld",
    "Melee",
    "Memory Counters",
    "Menace",
    "Menace Counters",
    "Mentor",
    "Mercenary Tokens",
    "Merfolk Tokens",
    "Merfolk Wizard Tokens",
    "Metalcraft",
    "Metallic Sliver Tokens",
    "Meteorite Tokens",
    "Midway Counters",
    "Mill",
    "Mine Counters",
    "Mining Counters",
    "Minion Tokens",
    "Minotaur Tokens",
    "Miracle",
    "Mire Counters",
    "Mishra's Warform Tokens",
    "Modular",
    "Monarch",
    "Monk Tokens",
    "Monstrosity",
    "Moonfolk Tokens",
    "Morbid",
    "More Counters",
    "Morph",
    "Mounts",
    "Mouse Tokens",
    "Multicolored",
    "Multikicker",
    "Music Counters",
    "Muster Counters",
    "Mutant Tokens",
    "Mutate",
    "Myr Tokens",
    "Myriad",
    "N Color",
    "N Identity",
    "Necrodermis Counters",
    "Necron Warrior Tokens",
    "Nest Counters",
    "Net Counters",
    "Night Counters",
    "Nightmare Horror Tokens",
    "Nightmare Tokens",
    "Ninja Tokens",
    "Ninjutsu",
    "No Counters",
    "Octopus Tokens",
    "Of Counters",
    "Offering",
    "Offspring",
    "Ogre Tokens",
    "Ogre Warrior Tokens",
    "Oil Counters",
    "Oketra's Attendant Tokens",
    "Omen Counters",
    "Ooze Tokens",
    "Orc Army Tokens",
    "Ore Counters",
    "Ornithopter Tokens",
    "Osgood, Operation Double Tokens",
    "Otter Tokens",
    "Outlaw",
    "Overload",
    "Ox Tokens",
    "Pack Tactics",
    "Page Counters",
    "Pain Counters",
    "Palliation Counters",
    "Paradox",
    "Paralyzation Counters",
    "Parley",
    "Partner",
    "Party",
    "Pause Counters",
    "Pawpatch Recruit Tokens",
    "Pay Life",
    "Pegasus Tokens",
    "Pentavite Tokens",
    "Persist",
    "Pest Tokens",
    "Petal Counters",
    "Petrification Counters",
    "Phasing",
    "Phobos Tokens",
    "Phylactery Counters",
    "Phyresis Counters",
    "Phyrexian Beast Tokens",
    "Phyrexian Germ Tokens",
    "Phyrexian Goblin Tokens",
    "Phyrexian Golem Tokens",
    "Phyrexian Horror Tokens",
    "Phyrexian Hydra Tokens",
    "Phyrexian Insect Tokens",
    "Phyrexian Mite Tokens",
    "Phyrexian Myr Tokens",
    "Phyrexian Saproling Tokens",
    "Phyrexian Tokens",
    "Phyrexian Wurm Tokens",
    "Pilot Tokens",
    "Pin Counters",
    "Pirate Tokens",
    "Plague Counters",
    "Plaguebearer of Nurgle Tokens",
    "Plant Tokens",
    "Plant Warrior Tokens",
    "Plot",
    "Plot Counters",
    "Point Counters",
    "Poison",
    "Poison Counters",
    "Polyp Counters",
    "Populate",
    "Possession Counters",
    "Powerstone Tokens",
    "Pressure Counters",
    "Prey Counters",
    "Primeval Counters",
    "Primo, the Indivisible Tokens",
    "Proliferate",
    "Prosperous Bandit Tokens",
    "Protection",
    "Prototype",
    "Proven Combatant Tokens",
    "Provoke",
    "Prowess",
    "Prowl",
    "Pupa Counters",
    "Quest Counters",
    "R Color",
    "R Identity",
    "RU Color",
    "RU Identity",
    "RUW Color",
    "RUW Identity",
    "RW Color",
    "RW Identity",
    "Rabbit Tokens",
    "Raccoon Tokens",
    "Rad Counters",
    "Radiance",
    "Ragavan Tokens",
    "Raid",
    "Rally",
    "Rampage",
    "Rat Rogue Tokens",
    "Rat Tokens",
    "Ravage Tokens",
    "Ravenous",
    "Reach",
    "Reach Counters",
    "Read Ahead",
    "Reanimation",
    "Rebel Tokens",
    "Rebound",
    "Rebuilding Counters",
    "Reconfigure",
    "Recover",
    "Reflection Tokens",
    "Regenerate",
    "Reinforce",
    "Rejection Counters",
    "Release Counters",
    "Renown",
    "Replicated Ring Tokens",
    "Reprieve Counters",
    "Resilient Khenra Tokens",
    "Resonance Counters",
    "Retrace",
    "Rev Counters",
    "Revival Counters",
    "Revolt",
    "Rhino Tokens",
    "Rhino Warrior Tokens",
    "Ribbon Counters",
    "Riot",
    "Ripple",
    "Robot Tokens",
    "Rock Tokens",
    "Rogue Tokens",
    "Roll Dice",
    "Rope Counters",
    "Rukh Tokens",
    "Rust Counters",
    "Rust-Shield Rampager Tokens",
    "Sacred Cat Tokens",
    "Sacrifice",
    "Salamander Warrior Tokens",
    "Samurai Tokens",
    "Sand Warrior Tokens",
    "Saproling Tokens",
    "Satyr Tokens",
    "Scarecrow Tokens",
    "Scavenge",
    "Scion of the Deep Tokens",
    "Scorpion Dragon Tokens",
    "Scrap Tokens",
    "Scream Counters",
    "Scroll Counters",
    "Scry",
    "Sculpture Tokens",
    "Secret Council",
    "Serf Tokens",
    "Servo Tokens",
    "Settlement Tokens",
    "Shadow",
    "Shadow Counters",
    "Shapeshifter Tokens",
    "Shard Tokens",
    "Shark Tokens",
    "Sheep Tokens",
    "Shell Counters",
    "Shield Counters",
    "Shoe Counters",
    "Shred Counters",
    "Shrine Tokens",
    "Shroud",
    "Shy Counters",
    "Sicarian Infiltrator Tokens",
    "Silver Counters",
    "Sinuous Striker Tokens",
    "Six Counters",
    "Skeleton Pirate Tokens",
    "Skeleton Tokens",
    "Skewer Counters",
    "Skulk",
    "Sleep Counters",
    "Sleight Counters",
    "Slime Counters",
    "Sliver Army Tokens",
    "Sliver Tokens",
    "Slug Tokens",
    "Slumber Counters",
    "Smaug Tokens",
    "Smoke Blessing Tokens",
    "Snail Tokens",
    "Snake Tokens",
    "Snow",
    "Soldier Ally Tokens",
    "Soldier Tokens",
    "Soot Counters",
    "Soul Counters",
    "Soulbond",
    "Soulshift",
    "Space Marine Devastator Tokens",
    "Spark Elemental Tokens",
    "Spawn Tokens",
    "Spectacle",
    "Spell Counters",
    "Spell Mastery",
    "Spellgorger Weird Tokens",
    "Sphinx Tokens",
    "Spider Tokens",
    "Spirit Cleric Tokens",
    "Spirit Tokens",
    "Spirit Warrior Tokens",
    "Spite Counters",
    "Splash Lasher Tokens",
    "Splice",
    "Split Second",
    "Spore Counters",
    "Spree",
    "Squad",
    "Squid Tokens",
    "Squirrel Tokens",
    "Stangg Twin Tokens",
    "Starscape Cleric Tokens",
    "Stash Counters",
    "Steadfast Sentinel Tokens",
    "Steampath Charger Tokens",
    "Steelburr Champion Tokens",
    "Stoneforged Blade Tokens",
    "Storage Counters",
    "Storm",
    "Storm Crow Tokens",
    "Story Counters",
    "Strife Counters",
    "Strike Counters",
    "Strive",
    "Stroopwafel Counters",
    "Study Counters",
    "Stun Counters",
    "Sunburst",
    "Sunscourge Champion Tokens",
    "Supply Counters",
    "Support",
    "Surge",
    "Surveil",
    "Survivor Tokens",
    "Suspect",
    "Suspect Counters",
    "Suspend",
    "Sword Tokens",
    "Tah-Crop Skirmisher Tokens",
    "Takeover Counters",
    "Tamiyo's Notebook Tokens",
    "Tarmogoyf Tokens",
    "Task Counters",
    "Teddy Bear Tokens",
    "Temmet, Vizier of Naktamun Tokens",
    "Tempting Offer",
    "Tender Wildguide Tokens",
    "Tentacle Tokens",
    "That Counters",
    "The Atropal Tokens",
    "The Hollow Sentinel Tokens",
    "The Ring Tempts",
    "Theft Counters",
    "Then Counters",
    "Thopter Tokens",
    "Thornplate Intimidator Tokens",
    "Those Counters",
    "Three Counters",
    "Threshold",
    "Thrull Tokens",
    "Thundertrap Trainer Tokens",
    "Tide Counters",
    "Time Counters",
    "Time Travel",
    "Timeless Dragon Tokens",
    "Timeless Witness Tokens",
    "Tiny Tokens",
    "Token Counters",
    "Tower Counters",
    "Toxic",
    "Toy Tokens",
    "Training",
    "Training Counters",
    "Trample",
    "Trample Counters",
    "Transfigure",
    "Transform",
    "Transmute",
    "Trap Counters",
    "Treasure Counters",
    "Treasure Tokens",
    "Treefolk Shaman Tokens",
    "Treefolk Tokens",
    "Treefolk Warrior Tokens",
    "Triskelavite Tokens",
    "Troll Warrior Tokens",
    "Trueheart Duelist Tokens",
    "Tuktuk the Returned Tokens",
    "Turned Face Up",
    "Tutor",
    "Twenty Counters",
    "Tyranid Gargoyle Tokens",
    "Tyranid Tokens",
    "Tyranid Warrior Tokens",
    "U Color",
    "U Identity",
    "UW Color",
    "UW Identity",
    "Ultramarines Honour Guard Tokens",
    "Umbra Armor",
    "Unblockable",
    "Uncounterable",
    "Undaunted",
    "Undergrowth",
    "Undying",
    "Unearth",
    "Unity Counters",
    "Unleash",
    "Unlock Counters",
    "Unwavering Initiate Tokens",
    "Upkeep",
    "Valiant",
    "Valor Counters",
    "Vampire Demon Tokens",
    "Vampire Knight Tokens",
    "Vampire Rogue Tokens",
    "Vampire Tokens",
    "Vanguard Suppressor Tokens",
    "Vanishing",
    "Varmint Tokens",
    "Vecna Tokens",
    "Velocity Counters",
    "Verse Counters",
    "Vigilance",
    "Vigilance Counters",
    "Vitality Counters",
    "Vizier of Many Faces Tokens",
    "Void Counters",
    "Voja Fenstalker Tokens",
    "Voja Tokens",
    "Voja, Friend to Elves Tokens",
    "Volo's Journal Tokens",
    "Vortex Counters",
    "Voting",
    "Vow Counters",
    "W Color",
    "W Identity",
    "Wage Counters",
    "Walker Tokens",
    "Wall Tokens",
    "Ward",
    "Warren Warleader Tokens",
    "Warrior Tokens",
    "Wasp Tokens",
    "Wasteland Survival Guide Tokens",
    "Weird Tokens",
    "Whale Tokens",
    "Will of the Council",
    "Will of the Planeswalkers",
    "Winch Counters",
    "Wind Counters",
    "Wish Counters",
    "With Counters",
    "Wither",
    "Wizard Tokens",
    "Wolf Tokens",
    "Worm Tokens",
    "Would Counters",
    "Wraith Tokens",
    "Wurm Tokens",
    "X Counters",
    "Zephyrim Tokens",
    "Zombie Army Tokens",
    "Zombie Berserker Tokens",
    "Zombie Employee Tokens",
    "Zombie Giant Tokens",
    "Zombie Horror Tokens",
    "Zombie Knight Tokens",
    "Zombie Mutant Tokens",
    "Zombie Rogue Tokens",
    "Zombie Tokens",
    "Zombie Warrior Tokens",
    "Zombie Wizard Tokens",
    "{0} Cost",
    "{1000000} Cost",
    "{10} Cost",
    "{10}{B} Cost",
    "{10}{B}{B} Cost",
    "{10}{G} Cost",
    "{10}{G}{G} Cost",
    "{10}{G}{G}{G}{W}{W} Cost",
    "{10}{R}{R} Cost",
    "{10}{U}{U} Cost",
    "{11} Cost",
    "{12} Cost",
    "{12}{U}{U} Cost",
    "{13} Cost",
    "{13}{B}{B} Cost",
    "{14}{G} Cost",
    "{15} Cost",
    "{16} Cost",
    "{1} Cost",
    "{1}{2/U}{2/R} Cost",
    "{1}{B/G} Cost",
    "{1}{B/G}{B/G} Cost",
    "{1}{B/G}{B/G}{B/G} Cost",
    "{1}{B/G}{R} Cost",
    "{1}{B/P} Cost",
    "{1}{B/P}{B/P} Cost",
    "{1}{B/R} Cost",
    "{1}{B/R}{B/R} Cost",
    "{1}{B/R}{B/R}{B/R} Cost",
    "{1}{B/R}{R}{R/G} Cost",
    "{1}{B} Cost",
    "{1}{B}{B/G}{G} Cost",
    "{1}{B}{B} Cost",
    "{1}{B}{B}{B} Cost",
    "{1}{B}{B}{B}{B} Cost",
    "{1}{B}{B}{B}{G}{G}{G} Cost",
    "{1}{B}{B}{G} Cost",
    "{1}{B}{B}{R}{R} Cost",
    "{1}{B}{G} Cost",
    "{1}{B}{G}{G} Cost",
    "{1}{B}{G}{U} Cost",
    "{1}{B}{R} Cost",
    "{1}{B}{R}{G} Cost",
    "{1}{B}{R}{R} Cost",
    "{1}{C} Cost",
    "{1}{C}{G} Cost",
    "{1}{C}{R} Cost",
    "{1}{G/U} Cost",
    "{1}{G/U}{G/U} Cost",
    "{1}{G/W} Cost",
    "{1}{G/W}{G/W} Cost",
    "{1}{G/W}{G/W}{G/W} Cost",
    "{1}{G} Cost",
    "{1}{G}{2/U}{2/R} Cost",
    "{1}{G}{G/U}{U} Cost",
    "{1}{G}{G/W/P}{W} Cost",
    "{1}{G}{G} Cost",
    "{1}{G}{G}{G} Cost",
    "{1}{G}{G}{G}{G} Cost",
    "{1}{G}{G}{U} Cost",
    "{1}{G}{G}{W} Cost",
    "{1}{G}{G}{W}{W} Cost",
    "{1}{G}{U} Cost",
    "{1}{G}{U}{R} Cost",
    "{1}{G}{U}{U} Cost",
    "{1}{G}{W} Cost",
    "{1}{G}{W}{U} Cost",
    "{1}{G}{W}{W} Cost",
    "{1}{R/G} Cost",
    "{1}{R/G}{R/G}{R/G} Cost",
    "{1}{R/W} Cost",
    "{1}{R/W}{R/W} Cost",
    "{1}{R} Cost",
    "{1}{R}{G} Cost",
    "{1}{R}{G}{G} Cost",
    "{1}{R}{G}{W} Cost",
    "{1}{R}{G}{W}{U} Cost",
    "{1}{R}{R/W/P}{W} Cost",
    "{1}{R}{R} Cost",
    "{1}{R}{R}{R} Cost",
    "{1}{R}{R}{R}{R} Cost",
    "{1}{R}{R}{W} Cost",
    "{1}{R}{W} Cost",
    "{1}{R}{W}{B} Cost",
    "{1}{R}{W}{W} Cost",
    "{1}{U/B} Cost",
    "{1}{U/B}{U/B} Cost",
    "{1}{U/B}{U/B}{G}{G} Cost",
    "{1}{U/B}{U/B}{U/B} Cost",
    "{1}{U/R} Cost",
    "{1}{U/R}{U/R} Cost",
    "{1}{U} Cost",
    "{1}{U}{B} Cost",
    "{1}{U}{B}{B} Cost",
    "{1}{U}{B}{R} Cost",
    "{1}{U}{G} Cost",
    "{1}{U}{R} Cost",
    "{1}{U}{R}{W} Cost",
    "{1}{U}{U/R}{R} Cost",
    "{1}{U}{U} Cost",
    "{1}{U}{U}{B} Cost",
    "{1}{U}{U}{R} Cost",
    "{1}{U}{U}{U} Cost",
    "{1}{U}{U}{U}{U} Cost",
    "{1}{W/B} Cost",
    "{1}{W/B}{W/B} Cost",
    "{1}{W/P} Cost",
    "{1}{W/U} Cost",
    "{1}{W/U}{W/U} Cost",
    "{1}{W/U}{W/U}{W/U} Cost",
    "{1}{W} Cost",
    "{1}{W}{B} Cost",
    "{1}{W}{B}{B} Cost",
    "{1}{W}{B}{G} Cost",
    "{1}{W}{U} Cost",
    "{1}{W}{U}{B} Cost",
    "{1}{W}{U}{B}{R}{G} Cost",
    "{1}{W}{U}{G} Cost",
    "{1}{W}{W} Cost",
    "{1}{W}{W}{B} Cost",
    "{1}{W}{W}{B}{B} Cost",
    "{1}{W}{W}{U} Cost",
    "{1}{W}{W}{U}{U} Cost",
    "{1}{W}{W}{W} Cost",
    "{1}{W}{W}{W}{W} Cost",
    "{2/B}{2/B}{2/B} Cost",
    "{2/G}{2/G}{2/G} Cost",
    "{2/R}{2/R}{2/R} Cost",
    "{2/U}{2/U}{2/U} Cost",
    "{2/W}{2/U}{2/B}{2/R}{2/G} Cost",
    "{2/W}{2/W}{2/W} Cost",
    "{2} Cost",
    "{2}{B/G} Cost",
    "{2}{B/G}{B/G} Cost",
    "{2}{B/G}{B/G}{B/G} Cost",
    "{2}{B/P}{B/P} Cost",
    "{2}{B/R} Cost",
    "{2}{B/R}{B/R} Cost",
    "{2}{B} Cost",
    "{2}{B}{B} Cost",
    "{2}{B}{B}{B} Cost",
    "{2}{B}{B}{G}{G} Cost",
    "{2}{B}{B}{R} Cost",
    "{2}{B}{B}{R}{R} Cost",
    "{2}{B}{B}{R}{R}{G}{G} Cost",
    "{2}{B}{G} Cost",
    "{2}{B}{G}{G} Cost",
    "{2}{B}{G}{U} Cost",
    "{2}{B}{R} Cost",
    "{2}{B}{R}{G} Cost",
    "{2}{B}{R}{R} Cost",
    "{2}{C} Cost",
    "{2}{C}{C} Cost",
    "{2}{G/U} Cost",
    "{2}{G/U}{G/U}{G/U} Cost",
    "{2}{G/U}{W} Cost",
    "{2}{G/W} Cost",
    "{2}{G/W}{G/W} Cost",
    "{2}{G/W}{G/W}{G/W} Cost",
    "{2}{G} Cost",
    "{2}{G}{G/U/P}{U} Cost",
    "{2}{G}{G} Cost",
    "{2}{G}{G}{G} Cost",
    "{2}{G}{G}{G}{G} Cost",
    "{2}{G}{G}{U} Cost",
    "{2}{G}{G}{U}{U} Cost",
    "{2}{G}{G}{W} Cost",
    "{2}{G}{G}{W}{W} Cost",
    "{2}{G}{G}{W}{W}{U}{U} Cost",
    "{2}{G}{U} Cost",
    "{2}{G}{U}{R} Cost",
    "{2}{G}{U}{U} Cost",
    "{2}{G}{W} Cost",
    "{2}{G}{W}{U} Cost",
    "{2}{G}{W}{W} Cost",
    "{2}{R/G} Cost",
    "{2}{R/G}{R/G} Cost",
    "{2}{R/G}{U} Cost",
    "{2}{R/W} Cost",
    "{2}{R/W}{G} Cost",
    "{2}{R/W}{R/W} Cost",
    "{2}{R/W}{R/W}{R/W} Cost",
    "{2}{R} Cost",
    "{2}{R}{D} Cost",
    "{2}{R}{G} Cost",
    "{2}{R}{G}{W} Cost",
    "{2}{R}{R/G/P}{G} Cost",
    "{2}{R}{R} Cost",
    "{2}{R}{R}{G} Cost",
    "{2}{R}{R}{G}{G} Cost",
    "{2}{R}{R}{G}{G}{W}{W} Cost",
    "{2}{R}{R}{R} Cost",
    "{2}{R}{R}{R}{G} Cost",
    "{2}{R}{R}{R}{R} Cost",
    "{2}{R}{R}{W} Cost",
    "{2}{R}{R}{W}{W} Cost",
    "{2}{R}{R}{W}{W}{B}{B} Cost",
    "{2}{R}{W} Cost",
    "{2}{R}{W}{B} Cost",
    "{2}{U/B} Cost",
    "{2}{U/B}{B}{B/R} Cost",
    "{2}{U/B}{U/B} Cost",
    "{2}{U/P} Cost",
    "{2}{U/R} Cost",
    "{2}{U/R}{B} Cost",
    "{2}{U/R}{U/R} Cost",
    "{2}{U} Cost",
    "{2}{U}{B} Cost",
    "{2}{U}{B}{R} Cost",
    "{2}{U}{G} Cost",
    "{2}{U}{R} Cost",
    "{2}{U}{R}{W} Cost",
    "{2}{U}{U/P} Cost",
    "{2}{U}{U} Cost",
    "{2}{U}{U}{B} Cost",
    "{2}{U}{U}{B}{B} Cost",
    "{2}{U}{U}{B}{B}{R}{R} Cost",
    "{2}{U}{U}{R} Cost",
    "{2}{U}{U}{R}{R} Cost",
    "{2}{U}{U}{U} Cost",
    "{2}{U}{U}{U}{U} Cost",
    "{2}{W/B} Cost",
    "{2}{W/B}{U} Cost",
    "{2}{W/B}{W/B} Cost",
    "{2}{W/B}{W/B}{W/B} Cost",
    "{2}{W/P} Cost",
    "{2}{W/U} Cost",
    "{2}{W/U}{W/U} Cost",
    "{2}{W} Cost",
    "{2}{W}{B} Cost",
    "{2}{W}{B}{B} Cost",
    "{2}{W}{B}{G} Cost",
    "{2}{W}{R}{G} Cost",
    "{2}{W}{U} Cost",
    "{2}{W}{U}{B} Cost",
    "{2}{W}{U}{B}{R}{G} Cost",
    "{2}{W}{U}{U} Cost",
    "{2}{W}{U}{U}{B} Cost",
    "{2}{W}{W} Cost",
    "{2}{W}{W}{B} Cost",
    "{2}{W}{W}{B}{B} Cost",
    "{2}{W}{W}{U} Cost",
    "{2}{W}{W}{U}{U} Cost",
    "{2}{W}{W}{U}{U}{B}{B} Cost",
    "{2}{W}{W}{W} Cost",
    "{2}{W}{W}{W}{W} Cost",
    "{3} Cost",
    "{3}{B/G} Cost",
    "{3}{B/G}{B/G} Cost",
    "{3}{B/G}{B/G}{B/G} Cost",
    "{3}{B/G}{R} Cost",
    "{3}{B/R}{B/R} Cost",
    "{3}{B} Cost",
    "{3}{B}{B} Cost",
    "{3}{B}{B}{B} Cost",
    "{3}{B}{B}{B}{B} Cost",
    "{3}{B}{B}{G} Cost",
    "{3}{B}{B}{R} Cost",
    "{3}{B}{B}{R}{R} Cost",
    "{3}{B}{G} Cost",
    "{3}{B}{G}{U} Cost",
    "{3}{B}{R} Cost",
    "{3}{B}{R}{G} Cost",
    "{3}{B}{R}{R} Cost",
    "{3}{C} Cost",
    "{3}{C}{C} Cost",
    "{3}{C}{C}{C} Cost",
    "{3}{G/P} Cost",
    "{3}{G/U} Cost",
    "{3}{G/U}{G/U} Cost",
    "{3}{G/U}{G/U}{G/U} Cost",
    "{3}{G/W} Cost",
    "{3}{G/W}{G/W} Cost",
    "{3}{G} Cost",
    "{3}{G}{G} Cost",
    "{3}{G}{G}{G/P}{G/P} Cost",
    "{3}{G}{G}{G} Cost",
    "{3}{G}{G}{G}{G} Cost",
    "{3}{G}{G}{U}{U} Cost",
    "{3}{G}{G}{W} Cost",
    "{3}{G}{G}{W}{W} Cost",
    "{3}{G}{U} Cost",
    "{3}{G}{U}{R} Cost",
    "{3}{G}{U}{U} Cost",
    "{3}{G}{W} Cost",
    "{3}{G}{W}{U} Cost",
    "{3}{G}{W}{U}{B} Cost",
    "{3}{G}{W}{W} Cost",
    "{3}{R/G} Cost",
    "{3}{R/G}{R/G} Cost",
    "{3}{R/P} Cost",
    "{3}{R/P}{R/P} Cost",
    "{3}{R/W} Cost",
    "{3}{R/W}{R/W} Cost",
    "{3}{R} Cost",
    "{3}{R}{G} Cost",
    "{3}{R}{G}{G} Cost",
    "{3}{R}{G}{W} Cost",
    "{3}{R}{R/W}{W} Cost",
    "{3}{R}{R} Cost",
    "{3}{R}{R}{G} Cost",
    "{3}{R}{R}{G}{G} Cost",
    "{3}{R}{R}{R} Cost",
    "{3}{R}{R}{R}{R} Cost",
    "{3}{R}{R}{W} Cost",
    "{3}{R}{W} Cost",
    "{3}{R}{W}{B} Cost",
    "{3}{R}{W}{W} Cost",
    "{3}{U/B} Cost",
    "{3}{U/B}{U/B} Cost",
    "{3}{U/B}{U/B}{U/B} Cost",
    "{3}{U/P} Cost",
    "{3}{U/R} Cost",
    "{3}{U/R}{B} Cost",
    "{3}{U/R}{U/R} Cost",
    "{3}{U/R}{U/R}{U/R} Cost",
    "{3}{U} Cost",
    "{3}{U}{B} Cost",
    "{3}{U}{B}{B} Cost",
    "{3}{U}{B}{R} Cost",
    "{3}{U}{R} Cost",
    "{3}{U}{R}{R} Cost",
    "{3}{U}{R}{W} Cost",
    "{3}{U}{U} Cost",
    "{3}{U}{U}{B} Cost",
    "{3}{U}{U}{B}{B} Cost",
    "{3}{U}{U}{R}{R} Cost",
    "{3}{U}{U}{U} Cost",
    "{3}{W/B} Cost",
    "{3}{W/B}{W/B} Cost",
    "{3}{W/B}{W/B}{W/B} Cost",
    "{3}{W/P}{W/P} Cost",
    "{3}{W/U} Cost",
    "{3}{W/U}{W/U} Cost",
    "{3}{W/U}{W/U}{W/U} Cost",
    "{3}{W} Cost",
    "{3}{W}{B} Cost",
    "{3}{W}{B}{B} Cost",
    "{3}{W}{B}{G} Cost",
    "{3}{W}{U} Cost",
    "{3}{W}{U}{B} Cost",
    "{3}{W}{U}{B}{R}{G} Cost",
    "{3}{W}{U}{U} Cost",
    "{3}{W}{W} Cost",
    "{3}{W}{W}{B}{B} Cost",
    "{3}{W}{W}{U} Cost",
    "{3}{W}{W}{U}{U} Cost",
    "{3}{W}{W}{W} Cost",
    "{3}{W}{W}{W}{W} Cost",
    "{4} Cost",
    "{4}{B/G} Cost",
    "{4}{B/G}{B/G} Cost",
    "{4}{B/G}{B/G}{B/G} Cost",
    "{4}{B/P} Cost",
    "{4}{B/P}{B/P}{B/P} Cost",
    "{4}{B/R} Cost",
    "{4}{B} Cost",
    "{4}{B}{B/P} Cost",
    "{4}{B}{B} Cost",
    "{4}{B}{B}{B} Cost",
    "{4}{B}{B}{B}{B} Cost",
    "{4}{B}{B}{G}{G} Cost",
    "{4}{B}{B}{R} Cost",
    "{4}{B}{B}{R}{R} Cost",
    "{4}{B}{G} Cost",
    "{4}{B}{G}{U} Cost",
    "{4}{B}{R} Cost",
    "{4}{B}{R}{G} Cost",
    "{4}{B}{R}{R} Cost",
    "{4}{B}{R}{R}{G} Cost",
    "{4}{C} Cost",
    "{4}{C}{C} Cost",
    "{4}{G/P}{G/P} Cost",
    "{4}{G/U}{G/U} Cost",
    "{4}{G/U}{G/U}{G/U} Cost",
    "{4}{G} Cost",
    "{4}{G}{G} Cost",
    "{4}{G}{G}{G} Cost",
    "{4}{G}{G}{G}{G} Cost",
    "{4}{G}{G}{U} Cost",
    "{4}{G}{G}{W}{W} Cost",
    "{4}{G}{U} Cost",
    "{4}{G}{W} Cost",
    "{4}{G}{W}{U} Cost",
    "{4}{G}{W}{W}{U} Cost",
    "{4}{R/G} Cost",
    "{4}{R/G}{R/G} Cost",
    "{4}{R/G}{R/G}{R/G} Cost",
    "{4}{R/P} Cost",
    "{4}{R/P}{R/P} Cost",
    "{4}{R} Cost",
    "{4}{R}{G} Cost",
    "{4}{R}{G}{G}{W} Cost",
    "{4}{R}{G}{W} Cost",
    "{4}{R}{R} Cost",
    "{4}{R}{R}{G} Cost",
    "{4}{R}{R}{G}{G} Cost",
    "{4}{R}{R}{R} Cost",
    "{4}{R}{R}{R}{R} Cost",
    "{4}{R}{R}{W} Cost",
    "{4}{R}{R}{W}{W} Cost",
    "{4}{R}{W} Cost",
    "{4}{R}{W}{B} Cost",
    "{4}{R}{W}{W} Cost",
    "{4}{U/B} Cost",
    "{4}{U/B}{U/B} Cost",
    "{4}{U/R}{U/R} Cost",
    "{4}{U} Cost",
    "{4}{U}{B} Cost",
    "{4}{U}{B}{B}{R} Cost",
    "{4}{U}{B}{R} Cost",
    "{4}{U}{R} Cost",
    "{4}{U}{R}{R} Cost",
    "{4}{U}{U} Cost",
    "{4}{U}{U}{U} Cost",
    "{4}{U}{U}{U}{U} Cost",
    "{4}{W/B}{W/B} Cost",
    "{4}{W/B}{W/B}{W/B} Cost",
    "{4}{W/U} Cost",
    "{4}{W/U}{W/U} Cost",
    "{4}{W/U}{W/U}{W/U}{W/U} Cost",
    "{4}{W} Cost",
    "{4}{W}{B} Cost",
    "{4}{W}{B}{B} Cost",
    "{4}{W}{B}{G} Cost",
    "{4}{W}{R} Cost",
    "{4}{W}{R}{G} Cost",
    "{4}{W}{U} Cost",
    "{4}{W}{U}{B} Cost",
    "{4}{W}{U}{B}{R}{G} Cost",
    "{4}{W}{U}{U}{B} Cost",
    "{4}{W}{W} Cost",
    "{4}{W}{W}{B}{B} Cost",
    "{4}{W}{W}{U} Cost",
    "{4}{W}{W}{W} Cost",
    "{5} Cost",
    "{5}{B/G}{B/G} Cost",
    "{5}{B/R} Cost",
    "{5}{B/R}{B/R}{B/R} Cost",
    "{5}{B} Cost",
    "{5}{B}{B} Cost",
    "{5}{B}{B}{B} Cost",
    "{5}{B}{G} Cost",
    "{5}{B}{R} Cost",
    "{5}{B}{R}{G} Cost",
    "{5}{C} Cost",
    "{5}{C}{C} Cost",
    "{5}{G} Cost",
    "{5}{G}{G} Cost",
    "{5}{G}{G}{G} Cost",
    "{5}{G}{U} Cost",
    "{5}{G}{U}{R} Cost",
    "{5}{G}{U}{U} Cost",
    "{5}{G}{W} Cost",
    "{5}{R/G} Cost",
    "{5}{R} Cost",
    "{5}{R}{G} Cost",
    "{5}{R}{G}{W} Cost",
    "{5}{R}{R} Cost",
    "{5}{R}{R}{R} Cost",
    "{5}{R}{W} Cost",
    "{5}{R}{W}{B} Cost",
    "{5}{U/R}{U/R} Cost",
    "{5}{U} Cost",
    "{5}{U}{B} Cost",
    "{5}{U}{B}{B} Cost",
    "{5}{U}{B}{R} Cost",
    "{5}{U}{G} Cost",
    "{5}{U}{R} Cost",
    "{5}{U}{U} Cost",
    "{5}{U}{U}{U} Cost",
    "{5}{U}{U}{U}{U} Cost",
    "{5}{W} Cost",
    "{5}{W}{B} Cost",
    "{5}{W}{B}{G} Cost",
    "{5}{W}{U} Cost",
    "{5}{W}{U}{B} Cost",
    "{5}{W}{U}{B}{R}{G} Cost",
    "{5}{W}{W} Cost",
    "{5}{W}{W}{U} Cost",
    "{5}{W}{W}{W} Cost",
    "{6} Cost",
    "{6}{B} Cost",
    "{6}{B}{B} Cost",
    "{6}{B}{B}{B} Cost",
    "{6}{B}{G} Cost",
    "{6}{B}{R} Cost",
    "{6}{C} Cost",
    "{6}{C}{C} Cost",
    "{6}{G} Cost",
    "{6}{G}{G} Cost",
    "{6}{G}{G}{G} Cost",
    "{6}{G}{W} Cost",
    "{6}{R} Cost",
    "{6}{R}{G} Cost",
    "{6}{R}{G}{W} Cost",
    "{6}{R}{R} Cost",
    "{6}{R}{R}{R} Cost",
    "{6}{U} Cost",
    "{6}{U}{B} Cost",
    "{6}{U}{G} Cost",
    "{6}{U}{R} Cost",
    "{6}{U}{U} Cost",
    "{6}{U}{U}{U} Cost",
    "{6}{W} Cost",
    "{6}{W}{B} Cost",
    "{6}{W}{W} Cost",
    "{6}{W}{W}{W} Cost",
    "{7} Cost",
    "{7}{B} Cost",
    "{7}{B}{B} Cost",
    "{7}{B}{B}{B} Cost",
    "{7}{B}{G} Cost",
    "{7}{G} Cost",
    "{7}{G}{G} Cost",
    "{7}{G}{G}{G} Cost",
    "{7}{R} Cost",
    "{7}{R}{R} Cost",
    "{7}{R}{R}{R} Cost",
    "{7}{U} Cost",
    "{7}{U}{U} Cost",
    "{7}{U}{U}{U} Cost",
    "{7}{W} Cost",
    "{7}{W}{U} Cost",
    "{7}{W}{W} Cost",
    "{7}{W}{W}{W} Cost",
    "{8} Cost",
    "{8}{B} Cost",
    "{8}{B}{B} Cost",
    "{8}{B}{B}{B} Cost",
    "{8}{B}{B}{G}{G} Cost",
    "{8}{B}{B}{R} Cost",
    "{8}{C/P}{C/P} Cost",
    "{8}{C}{C} Cost",
    "{8}{G} Cost",
    "{8}{G}{G} Cost",
    "{8}{G}{G}{G} Cost",
    "{8}{R} Cost",
    "{8}{R}{R} Cost",
    "{8}{U}{R} Cost",
    "{8}{U}{U} Cost",
    "{8}{U}{U}{U} Cost",
    "{8}{U}{U}{U}{U} Cost",
    "{8}{W}{W} Cost",
    "{9} Cost",
    "{9}{B} Cost",
    "{9}{C}{C}{C} Cost",
    "{9}{R} Cost",
    "{B/G} Cost",
    "{B/G}{B/G} Cost",
    "{B/G}{B/G}{B/G} Cost",
    "{B/G}{B/G}{B/G}{B/G} Cost",
    "{B/G}{B/G}{B/G}{B/G}{B/G} Cost",
    "{B/G}{R} Cost",
    "{B/P} Cost",
    "{B/R} Cost",
    "{B/R}{B/R} Cost",
    "{B/R}{B/R}{B/R} Cost",
    "{B/R}{B/R}{B/R}{B/R} Cost",
    "{B/R}{B/R}{B/R}{B/R}{B/R} Cost",
    "{B/R}{W/B} Cost",
    "{B} Cost",
    "{B}{B} Cost",
    "{B}{B}{B} Cost",
    "{B}{B}{B}{B} Cost",
    "{B}{B}{B}{B}{B}{B} Cost",
    "{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B}{B} Cost",
    "{B}{B}{G} Cost",
    "{B}{B}{G}{G} Cost",
    "{B}{B}{G}{G}{G}{U}{U} Cost",
    "{B}{B}{R} Cost",
    "{B}{B}{R}{R} Cost",
    "{B}{B}{R}{R}{R}{G}{G} Cost",
    "{B}{G} Cost",
    "{B}{G}{G} Cost",
    "{B}{G}{U} Cost",
    "{B}{R} Cost",
    "{B}{R}{G} Cost",
    "{B}{R}{G}{W} Cost",
    "{B}{R}{R} Cost",
    "{B}{U}{G} Cost",
    "{C/W}{C/U}{C/B}{C/R}{C/G} Cost",
    "{C} Cost",
    "{C}{W}{U}{B}{R}{G} Cost",
    "{C}{W}{U}{B}{R}{G}{S} Cost",
    "{G/P} Cost",
    "{G/U} Cost",
    "{G/U}{G/U} Cost",
    "{G/U}{G/U}{G/U} Cost",
    "{G/U}{G/U}{G/U}{G/U} Cost",
    "{G/U}{G/U}{G/U}{G/U}{G/U} Cost",
    "{G/U}{W} Cost",
    "{G/W} Cost",
    "{G/W}{G/U}{B/G}{R/G} Cost",
    "{G/W}{G/W} Cost",
    "{G/W}{G/W}{G/W} Cost",
    "{G/W}{G/W}{G/W}{G/W}{G/W} Cost",
    "{G/W}{W}{W/U} Cost",
    "{G} Cost",
    "{G}{G/W}{W} Cost",
    "{G}{G} Cost",
    "{G}{G}{G} Cost",
    "{G}{G}{G}{G} Cost",
    "{G}{G}{G}{G}{G} Cost",
    "{G}{G}{G}{G}{G}{G} Cost",
    "{G}{G}{G}{G}{G}{G}{G}{G} Cost",
    "{G}{G}{G}{U}{U}{U} Cost",
    "{G}{G}{G}{W}{W}{W} Cost",
    "{G}{G}{U} Cost",
    "{G}{G}{U}{U} Cost",
    "{G}{G}{U}{U}{U}{R}{R} Cost",
    "{G}{G}{W} Cost",
    "{G}{G}{W}{W} Cost",
    "{G}{G}{W}{W}{W}{U}{U} Cost",
    "{G}{U} Cost",
    "{G}{U}{R} Cost",
    "{G}{U}{U} Cost",
    "{G}{W} Cost",
    "{G}{W}{U} Cost",
    "{G}{W}{U}{B} Cost",
    "{G}{W}{W} Cost",
    "{HW} Cost",
    "{R/G} Cost",
    "{R/G}{G/W} Cost",
    "{R/G}{G}{G/W} Cost",
    "{R/G}{R/G} Cost",
    "{R/G}{R/G}{R/G} Cost",
    "{R/G}{R/G}{R/G}{R/G} Cost",
    "{R/G}{R/G}{R/G}{R/G}{R/G} Cost",
    "{R/G}{W}{U} Cost",
    "{R/P} Cost",
    "{R/W} Cost",
    "{R/W}{G} Cost",
    "{R/W}{R/W} Cost",
    "{R/W}{R/W}{R/W} Cost",
    "{R/W}{R/W}{R/W}{R/W} Cost",
    "{R/W}{R/W}{R/W}{R/W}{R/W} Cost",
    "{R} Cost",
    "{R}{G} Cost",
    "{R}{G}{U}{B} Cost",
    "{R}{G}{W} Cost",
    "{R}{G}{W}{U} Cost",
    "{R}{R} Cost",
    "{R}{R}{G} Cost",
    "{R}{R}{G}{G} Cost",
    "{R}{R}{G}{G}{G}{W}{W} Cost",
    "{R}{R}{R} Cost",
    "{R}{R}{R}{R} Cost",
    "{R}{R}{W}{W} Cost",
    "{R}{R}{W}{W}{W}{B}{B} Cost",
    "{R}{W} Cost",
    "{R}{W}{B} Cost",
    "{R}{W}{U} Cost",
    "{R}{W}{W} Cost",
    "{S} Cost",
    "{U/B} Cost",
    "{U/B}{U/B} Cost",
    "{U/B}{U/B}{U/B} Cost",
    "{U/B}{U/B}{U/B}{U/B} Cost",
    "{U/B}{U/B}{U/B}{U/B}{U/B} Cost",
    "{U/P} Cost",
    "{U/R} Cost",
    "{U/R}{B} Cost",
    "{U/R}{U/R} Cost",
    "{U/R}{U/R}{U/R} Cost",
    "{U/R}{U/R}{U/R}{U/R} Cost",
    "{U/R}{U/R}{U/R}{U/R}{U/R} Cost",
    "{U} Cost",
    "{U}{B} Cost",
    "{U}{B}{B} Cost",
    "{U}{B}{B}{B}{R} Cost",
    "{U}{B}{B}{R} Cost",
    "{U}{B}{R} Cost",
    "{U}{B}{R}{G} Cost",
    "{U}{R} Cost",
    "{U}{R}{R} Cost",
    "{U}{R}{W} Cost",
    "{U}{U/R}{R} Cost",
    "{U}{U} Cost",
    "{U}{U}{B} Cost",
    "{U}{U}{B}{B} Cost",
    "{U}{U}{B}{B}{B}{R}{R} Cost",
    "{U}{U}{R} Cost",
    "{U}{U}{R}{R} Cost",
    "{U}{U}{R}{R}{R}{W}{W} Cost",
    "{U}{U}{U} Cost",
    "{U}{U}{U}{R}{R}{R} Cost",
    "{U}{U}{U}{U} Cost",
    "{W/B} Cost",
    "{W/B}{U} Cost",
    "{W/B}{W/B} Cost",
    "{W/B}{W/B}{W/B} Cost",
    "{W/B}{W/B}{W/B}{W/B} Cost",
    "{W/B}{W/B}{W/B}{W/B}{W/B} Cost",
    "{W/P} Cost",
    "{W/U} Cost",
    "{W/U}{U}{U/B} Cost",
    "{W/U}{W/U} Cost",
    "{W/U}{W/U}{W/U} Cost",
    "{W/U}{W/U}{W/U}{W/U} Cost",
    "{W/U}{W/U}{W/U}{W/U}{W/U} Cost",
    "{W} Cost",
    "{W}{B} Cost",
    "{W}{B}{B} Cost",
    "{W}{B}{G} Cost",
    "{W}{U} Cost",
    "{W}{U}{B/P}{R}{G} Cost",
    "{W}{U}{B} Cost",
    "{W}{U}{B}{R} Cost",
    "{W}{U}{B}{R}{G} Cost",
    "{W}{U}{U} Cost",
    "{W}{U}{U}{B} Cost",
    "{W}{W/B}{B} Cost",
    "{W}{W} Cost",
    "{W}{W}{B} Cost",
    "{W}{W}{B}{B} Cost",
    "{W}{W}{B}{B}{B}{G}{G} Cost",
    "{W}{W}{U}{U} Cost",
    "{W}{W}{U}{U}{B}{B}{R}{R}{G}{G} Cost",
    "{W}{W}{U}{U}{U}{B}{B} Cost",
    "{W}{W}{W} Cost",
    "{W}{W}{W}{W} Cost",
    "{X} Cost",
    "{X}{1}{B} Cost",
    "{X}{1}{G} Cost",
    "{X}{1}{R}{R} Cost",
    "{X}{1}{R}{W} Cost",
    "{X}{1}{U} Cost",
    "{X}{1}{U}{U} Cost",
    "{X}{1}{W} Cost",
    "{X}{2}{B} Cost",
    "{X}{2}{B}{B} Cost",
    "{X}{2}{B}{R} Cost",
    "{X}{2}{G} Cost",
    "{X}{2}{G}{G} Cost",
    "{X}{2}{G}{U} Cost",
    "{X}{2}{R} Cost",
    "{X}{2}{R}{R} Cost",
    "{X}{2}{U} Cost",
    "{X}{2}{U}{B} Cost",
    "{X}{2}{W} Cost",
    "{X}{3}{B} Cost",
    "{X}{3}{B}{B} Cost",
    "{X}{3}{G} Cost",
    "{X}{3}{W} Cost",
    "{X}{4} Cost",
    "{X}{4}{B} Cost",
    "{X}{4}{G}{G} Cost",
    "{X}{5}{R} Cost",
    "{X}{6} Cost",
    "{X}{B/P} Cost",
    "{X}{B} Cost",
    "{X}{B}{B} Cost",
    "{X}{B}{B}{B} Cost",
    "{X}{B}{B}{B}{B} Cost",
    "{X}{B}{B}{G} Cost",
    "{X}{B}{G} Cost",
    "{X}{B}{G}{U} Cost",
    "{X}{B}{R} Cost",
    "{X}{B}{R}{G} Cost",
    "{X}{C}{C} Cost",
    "{X}{G/P} Cost",
    "{X}{G/U}{G/U} Cost",
    "{X}{G/W} Cost",
    "{X}{G} Cost",
    "{X}{G}{G} Cost",
    "{X}{G}{G}{G} Cost",
    "{X}{G}{G}{W} Cost",
    "{X}{G}{U} Cost",
    "{X}{G}{W} Cost",
    "{X}{G}{W}{U} Cost",
    "{X}{G}{W}{W} Cost",
    "{X}{R} Cost",
    "{X}{R}{G} Cost",
    "{X}{R}{G}{W} Cost",
    "{X}{R}{R} Cost",
    "{X}{R}{R}{G} Cost",
    "{X}{R}{R}{G}{G} Cost",
    "{X}{R}{R}{R} Cost",
    "{X}{R}{R}{W}{W} Cost",
    "{X}{R}{W} Cost",
    "{X}{U} Cost",
    "{X}{U}{B} Cost",
    "{X}{U}{R} Cost",
    "{X}{U}{U} Cost",
    "{X}{U}{U}{B} Cost",
    "{X}{U}{U}{R} Cost",
    "{X}{U}{U}{U} Cost",
    "{X}{U}{U}{U}{U} Cost",
    "{X}{W/B}{W/B}{W/B} Cost",
    "{X}{W} Cost",
    "{X}{W}{B} Cost",
    "{X}{W}{B}{G} Cost",
    "{X}{W}{U} Cost",
    "{X}{W}{U}{B} Cost",
    "{X}{W}{U}{B}{R}{G} Cost",
    "{X}{W}{U}{U} Cost",
    "{X}{W}{W} Cost",
    "{X}{W}{W}{B}{B} Cost",
    "{X}{W}{W}{W} Cost",
    "{X}{X} Cost",
    "{X}{X}{2}{W} Cost",
    "{X}{X}{2}{W}{W} Cost",
    "{X}{X}{B} Cost",
    "{X}{X}{B}{B}{B} Cost",
    "{X}{X}{B}{B}{B}{B} Cost",
    "{X}{X}{B}{R}{G} Cost",
    "{X}{X}{G} Cost",
    "{X}{X}{G}{G} Cost",
    "{X}{X}{G}{U} Cost",
    "{X}{X}{R} Cost",
    "{X}{X}{U} Cost",
    "{X}{X}{U}{U} Cost",
    "{X}{X}{U}{U}{U} Cost",
    "{X}{X}{U}{U}{U}{U} Cost",
    "{X}{X}{W} Cost",
    "{X}{X}{W}{W} Cost",
    "{X}{X}{W}{W}{W} Cost",
    "{X}{X}{X} Cost",
    "{X}{X}{X}{G}{U} Cost",
    "{X}{X}{X}{R}{R} Cost",
    "{X}{Y}{Z}{R}{R} Cost"
]

TYPE_LINE_OPTIONS = [
    "Abian",
    "Abyss",
    "Adventure",
    "Advisor",
    "Aetherborn",
    "Ajani",
    "Alara",
    "Alfava",
    "Alicorn",
    "Alien",
    "Ally",
    "Aminatou",
    "Amonkhet",
    "Amsterdam",
    "Androzani",
    "Angel",
    "Angrath",
    "Antausia",
    "Antelope",
    "Apalapucia",
    "Ape",
    "Arcane",
    "Arcavios",
    "Archer",
    "Archon",
    "Arkhos",
    "Arlinn",
    "Armadillo",
    "Armored",
    "Army",
    "Art",
    "Artifact",
    "Artificer",
    "Ashiok",
    "Assassin",
    "Assembly-Worker",
    "Astartes",
    "Asylum",
    "Athlete",
    "Atog",
    "Attraction",
    "Aura",
    "Aurochs",
    "Autobot",
    "Automaton",
    "Avatar",
    "Azgol",
    "Azra",
    "B.O.B.",
    "Background",
    "Baddest,",
    "Badger",
    "Bahamut",
    "Balloon",
    "Barbarian",
    "Bard",
    "Basic",
    "Basilisk",
    "Basri",
    "Bat",
    "Battle",
    "Bear",
    "Beast",
    "Beaver",
    "Beeble",
    "Beholder",
    "Belenon",
    "Berserker",
    "Beyondia",
    "Biggest,",
    "Bird",
    "Blind",
    "Blood",
    "Bloomburrow",
    "Boar",
    "Bobblehead",
    "Bolas",
    "Bolas's",
    "Boxer",
    "Brainiac",
    "Bringer",
    "Brushwagg",
    "Bureaucrat",
    "Byode",
    "C'tan",
    "Calix",
    "Camel",
    "Capenna",
    "Capybara",
    "Card",
    "Cards",
    "Carrier",
    "Cartouche",
    "Case",
    "Cat",
    "Cave",
    "Centaur",
    "Cephalid",
    "Chameleon",
    "Champion",
    "Chandra",
    "Chef",
    "Chicago",
    "Chicken",
    "Child",
    "Chimera",
    "Chorus",
    "Citizen",
    "Clamfolk",
    "Clamhattan",
    "Class",
    "Cleric",
    "Cloud",
    "Clown",
    "Clue",
    "Cockatrice",
    "Comet",
    "Conspiracy",
    "Construct",
    "Contraption",
    "Control",
    "Cow",
    "Coward",
    "Coyote",
    "Crab",
    "Creature",
    "Cridhe",
    "Crocodile",
    "Curse",
    "Custodes",
    "Cyberman",
    "Cyborg",
    "Cyclops",
    "Dack",
    "Dakkon",
    "Dalek",
    "Daretti",
    "Darillium",
    "Dauthi",
    "Davriel",
    "Deb",
    "Deer",
    "Demigod",
    "Demon",
    "Desert",
    "Designer",
    "Detective",
    "Devil",
    "Dihada",
    "Dinosaur",
    "Djinn",
    "Doctor",
    "Dog",
    "Dominaria",
    "Domri",
    "Donkey",
    "Dovin",
    "Dragon",
    "Drake",
    "Dreadnought",
    "Drone",
    "Druid",
    "Dryad",
    "Duck",
    "Dungeon",
    "Duskmourn",
    "Dwarf",
    "Earth",
    "Eaturecray",
    "Echoir",
    "Efreet",
    "Egg",
    "Elder",
    "Eldraine",
    "Eldrazi",
    "Elemental",
    "Elemental?",
    "Elephant",
    "Elf",
    "Elite",
    "Elk",
    "Ellywick",
    "Elminster",
    "Elspeth",
    "Elves",
    "Emblem",
    "Employee",
    "Enchantment",
    "Equilor",
    "Equipment",
    "Ergamon",
    "Ersta",
    "Estrid",
    "Eternities",
    "Etiquette",
    "Ever",
    "Eye",
    "Fabacin",
    "Faerie",
    "Ferret",
    "Fiora",
    "Fire",
    "Fish",
    "Flagbearer",
    "Foldaria",
    "Food",
    "Forest",
    "Fortification",
    "Fox",
    "Fractal",
    "Freyalise",
    "Frog",
    "Fungus",
    "Gallifrey",
    "Gamer",
    "Gargantikar",
    "Gargoyle",
    "Garruk",
    "Gate",
    "Germ",
    "Giant",
    "Gideon",
    "Gith",
    "Glimmer",
    "Gnoll",
    "Gnome",
    "Goat",
    "Gobakhan",
    "Goblin",
    "God",
    "Gold",
    "Golem",
    "Gorgon",
    "Grandchild",
    "Graveborn",
    "Gremlin",
    "Griffin",
    "Grist",
    "Guest",
    "Guff",
    "Gus",
    "Hag",
    "Halfling",
    "Hamster",
    "Harpy",
    "Hatificer",
    "Hawk",
    "Head",
    "Hell",
    "Hellion",
    "Hero",
    "Hippo",
    "Hippogriff",
    "Homarid",
    "Homunculus",
    "Horror",
    "Horse",
    "Horsehead",
    "Host",
    "Huatli",
    "Human",
    "Hydra",
    "Hyena",
    "Igpay",
    "Ikoria",
    "Illusion",
    "Imp",
    "Incarnation",
    "Incubator",
    "Inkling",
    "Innistrad",
    "Inquisitor",
    "Insect",
    "Instant",
    "Inzerva",
    "Iquatana",
    "Ir",
    "Island",
    "Ixalan",
    "Jace",
    "Jackal",
    "Jaguar",
    "Jared",
    "Jaya",
    "Jellyfish",
    "Jeska",
    "Judge",
    "Juggernaut",
    "Junction",
    "Junk",
    "Kaito",
    "Kaladesh",
    "Kaldheim",
    "Kamigawa",
    "Kandoka",
    "Kangaroo",
    "Karn",
    "Karsus",
    "Kasmina",
    "Kavu",
    "Kaya",
    "Kephalai",
    "Key",
    "Killbot",
    "Kindred",
    "Kinshala",
    "Kiora",
    "Kirin",
    "Kithkin",
    "Knight",
    "Knights",
    "Kobold",
    "Kolbahan",
    "Kor",
    "Koth",
    "Kraken",
    "Kylem",
    "Kyneth",
    "Lady",
    "Lair",
    "Lamia",
    "Lammasu",
    "Land",
    "Las",
    "Leech",
    "Legend",
    "Legendary",
    "Lesson",
    "Leviathan",
    "Lhurgoyf",
    "Library",
    "Licid",
    "Liliana",
    "Lizard",
    "Lobster",
    "Locus",
    "Lolth",
    "Lord",
    "Lorwyn",
    "Lukka",
    "Luvion",
    "Luxior",
    "MagicCon",
    "Mammoth",
    "Manticore",
    "Map",
    "Mars",
    "Master",
    "Masticore",
    "Meditation",
    "Mercadia",
    "Mercenary",
    "Merfolk",
    "Metathran",
    "Metraxis",
    "Mime",
    "Mine",
    "Minion",
    "Minor",
    "Minotaur",
    "Minsc",
    "Mirrodin",
    "Mission",
    "Mite",
    "Moag",
    "Mole",
    "Monger",
    "Mongoose",
    "Mongseng",
    "Monk",
    "Monkey",
    "Moon",
    "Moonfolk",
    "Mordenkainen",
    "Mount",
    "Mountain",
    "Mouse",
    "Mummy",
    "Muraganda",
    "Mutant",
    "Mutter's",
    "Myr",
    "Mystic",
    "Naga",
    "Nahiri",
    "Narset",
    "Nastiest,",
    "Nautilus",
    "Nebula",
    "Necron",
    "Necros",
    "Nephilim",
    "New",
    "Nightmare",
    "Nightstalker",
    "Niko",
    "Ninja",
    "Nissa",
    "Nixilis",
    "Noble",
    "Noggle",
    "Nomad",
    "Nymph",
    "Octopus",
    "Ogre",
    "Oko",
    "Omenpath",
    "Ongoing",
    "Ooze",
    "Orc",
    "Orgg",
    "Otter",
    "Ouphe",
    "Outside",
    "Ox",
    "Oyster",
    "Pangolin",
    "Paratrooper",
    "Peasant",
    "Pegasus",
    "Penguin",
    "Pentavite",
    "Performer",
    "Pest",
    "Phelddagrif",
    "Phenomenon",
    "Phoenix",
    "Phyrexia",
    "Phyrexian",
    "Pilot",
    "Pirate",
    "Plains",
    "Plane",
    "Planeswalker",
    "Planet",
    "Plant",
    "Point",
    "Poly",
    "Pony",
    "Porcupine",
    "Possum",
    "Power-Plant",
    "Powerstone",
    "Praetor",
    "Primarch",
    "Processor",
    "Proper",
    "Pyrulea",
    "Quest",
    "Quintorius",
    "Rabbit",
    "Rabiah",
    "Raccoon",
    "Ral",
    "Ranger",
    "Rat",
    "Rath",
    "Ravnica",
    "Realm",
    "Rebel",
    "Reflection",
    "Regatha",
    "Reveler",
    "Rhino",
    "Rigger",
    "Robot",
    "Rogue",
    "Role",
    "Room",
    "Rowan",
    "Rukh",
    "Rune",
    "Sable",
    "Saga",
    "Saheeli",
    "Salamander",
    "Samurai",
    "Samut",
    "Sand",
    "Saproling",
    "Sarkhan",
    "Satyr",
    "Scarecrow",
    "Scariest",
    "Scheme",
    "Scientist",
    "Scion",
    "Scorpion",
    "Scout",
    "Sculpture",
    "Secret",
    "See",
    "Segovia",
    "Serf",
    "Serpent",
    "Serra",
    "Serra\u2019s",
    "Servo",
    "Shade",
    "Shadowmoor",
    "Shaman",
    "Shandalar",
    "Shapeshifter",
    "Shard",
    "Shark",
    "Sheep",
    "Shenmeng",
    "Ship",
    "Shrine",
    "Siege",
    "Siren",
    "Sivitri",
    "Skaro",
    "Skeleton",
    "Skunk",
    "Slith",
    "Sliver",
    "Sloth",
    "Slug",
    "Snail",
    "Snake",
    "Snow",
    "Soldier",
    "Soltari",
    "Sorcery",
    "Sorin",
    "Spacecraft",
    "Spawn",
    "Specter",
    "Spellshaper",
    "Sphere",
    "Sphinx",
    "Spider",
    "Spike",
    "Spiral",
    "Spirit",
    "Splinter",
    "Sponge",
    "Spuzzem",
    "Spy",
    "Squid",
    "Squirrel",
    "Starfish",
    "Stickers",
    "Summon",
    "Surrakar",
    "Survivor",
    "Svega",
    "Swamp",
    "Synth",
    "Szat",
    "Tamiyo",
    "Tarkir",
    "Tasha",
    "Teddy",
    "Teferi",
    "Tentacle",
    "Teyo",
    "Tezzeret",
    "Thalakos",
    "Theros",
    "Thopter",
    "Thrull",
    "Thunder",
    "Tibalt",
    "Tiefling",
    "Time",
    "Token",
    "Tolkien",
    "Tower",
    "Town",
    "Townsfolk",
    "Toy",
    "Trap",
    "Treasure",
    "Tree",
    "Treefolk",
    "Trenzalore",
    "Tribal",
    "Trilobite",
    "Triskelavite",
    "Troll",
    "Turtle",
    "Tyranid",
    "Tyvar",
    "Ugin",
    "Ulamog's",
    "Ulgrotha",
    "Undercity",
    "Unicorn",
    "Universewalker",
    "Universia",
    "Unknown",
    "Urza",
    "Urza's",
    "Urzan",
    "Valla",
    "Vampire",
    "Vampyre",
    "Vanguard",
    "Varmint",
    "Vedalken",
    "Vegas",
    "Vehicle",
    "Venser",
    "Villain",
    "Vivien",
    "Volver",
    "Vraska",
    "Vronos",
    "Vryn",
    "Waiter",
    "Wall",
    "Walrus",
    "Wanderer",
    "Warlock",
    "Warrior",
    "Weasel",
    "Weird",
    "Werewolf",
    "Whale",
    "Wildfire",
    "Will",
    "Windgrace",
    "Wizard",
    "Wolf",
    "Wolverine",
    "Wombat",
    "World",
    "Worm",
    "Wraith",
    "Wrenn",
    "Wrestler",
    "Wurm",
    "Xenagos",
    "Xerex",
    "Yanggu",
    "Yanling",
    "Yeti",
    "You",
    "You'll",
    "Zariel",
    "Zendikar",
    "Zhalfir",
    "Zombie",
    "Zonian",
    "Zubera",
]